#!/system/xbin/bash

curr_user=`whoami`
eglfile=/system/lib/egl/egl.cfg

if [ "$curr_user" != "root" ]; then
	echo "this script can only be executed as 'root'"
	exit 1
fi

if [ "$1" != "enable" ] && [ "$1" != "disable" ]; then
	echo "usage: `basename $0` {enable|disable}"
	exit 1
fi

echo "mounting /system rw..."
if ! mount -o rw,remount /system; then
	echo "error mounting /system rw"
	exit 1
fi

if ! test -f ${eglfile}.disabled; then
	cp $eglfile ${eglfile}.disabled
fi

if ! test -f ${eglfile}.enabled; then
	cat ${eglfile} | tail -1 > ${eglfile}.enabled
fi

if [ "$1" == "enable" ]; then
	echo "enabling full GPU rendering..."
	cp ${eglfile}.enabled ${eglfile}
fi

if [ "$1" == "disable" ]; then
	echo "disabling full GPU rendering..."
	cp ${eglfile}.disabled ${eglfile}
fi

sync
sync
sync

if ! mount -o ro,remount /system; then
	echo "error mounting /system ro"
	exit 1
fi

echo "reboot for changes to take effect"
